import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id "org.jetbrains.kotlin.jvm" version "2.4.10" apply false
	id "org.jetbrains.kotlin.plugin.serialization" version "2.4.10" apply false
	id "kr.entree.spigradle" version "2.4.4" apply false
	id "net.fabricmc.fabric-loom" version "1.17-SNAPSHOT" apply false
	id "com.gradleup.shadow" version "9.6.1" apply false
}

repositories {
	mavenCentral()
}

allprojects {
	version = project.version
	group = project.group
}

subprojects {
	apply plugin: "java"
	
	repositories {
		mavenCentral()
	}
	
	tasks.withType(JavaCompile).configureEach {
		it.options.release = 25
	}

	tasks.withType(KotlinCompile).configureEach {
		kotlinOptions {
			jvmTarget = 25
		}
	}

	jar {
		from("LICENSE") {
			rename { "${it}_${project.base.archivesName.get()}"}
		}
	}
}
