plugins {
    id "org.jetbrains.kotlin.jvm"
    id "io.typst.spigradle.spigot"
    id "com.gradleup.shadow"
}

repositories {
    spigotRepos {
        spigotmc()
    }
}

dependencies {
    compileOnly(spigots.spigot.api)

    shadow(implementation(project ":dynmapexport-common"))
}

processResources {
    filesMatching("plugin.yml") {
        expand project.properties
    }
}

shadowJar {
    configurations = [project.configurations.shadow]
    exclude "META-INF"
}

build {
    dependsOn shadowJar
    mustRunAfter shadowJar
}
